### ISSUE TITLE
service catalog and button imports failed with "unknown attribute 'applies_to_exp' for CustomButton"

### ISSUE THREAD

**Issue by branic** [rhtconsulting/cfme-rhconsulting-scripts#111]
The Service Catalog has a button attached to it so the fix is probably the same for both the Custom Button and Service Catalog imports.

The export was performed from 4.5.2 and attempting to import into 4.6.0

**Comment by ramrexx** [comment]
I think we just need to skip the applies_to_exp if it is nil or we could rescue it out, or maybe something like:

          custom_button['applies_to_exp'] = cb['applies_to_exp'] if cb['applies_to_exp']
