### ISSUE TITLE
Create a CLI to use the scripts

### ISSUE THREAD

**Issue by georgegoh** [rhtconsulting/cfme-rhconsulting-scripts#12]
A command-line interface for the scripts to make it easy to perform import/export tasks, instead of using rake commands.

A possible approach could be to use Thor(http://whatisthor.com/) to do this:

cfexport <object-type> --exportdir <dir> --otheroptions
cfimport <object-type> --importdir <dir> --otheroptions

e.g.,
 cfexport domain --exportdir /tmp/cf/domain/ --domain ACME # export the ACME domain
 cfimport domain --importdir /tmp/cf/domain/ --domain ACME # import the ACME domain

**Comment by claudiol** [comment]
Looks like a neat tool. The only thing that I would be careful of is introducing new gems to the appliance. Our tools should stay within the gems that are supported by the CFME engine. That said, we can always suggest to add new gems if we feels it would help everyone.

**Comment by ramrexx** [comment]
Nice work. After looking at it i wonder if we should change the scripts to use miqexport and miqimport instead of cfme as its prefix?  Thoughts?

**Comment by claudiol** [comment]
+1 I think that's a good idea.

Lester Claudio
Cloud Domain Architect
Red Hat Inc
Cell: 719-331-0726
Office: 650-254-4175

**Comment by georgegoh** [comment]
Agree, I think miqexport/miqimport sound good.

**Comment by georgegoh** [comment]
Fixed in Pull Request #18
