### ISSUE TITLE
Resource Action for Service Dialogs differs from WebUI Export

### ISSUE THREAD

**Issue by hyclak** [rhtconsulting/cfme-rhconsulting-scripts#21]
Exporting from the WebUI replaces the resource_action_fqname string with a resource_action hash. e.g.:

    @@ -273,7 +322,14 @@
             read_only: true
             auto_refresh: 
             trigger_auto_refresh: 
    -        resource_action_fqname: "/Service/ServiceDialogs/DynamicTextAreaBoxes/Disclaimer"
    +        resource_action:
    +          action: 
    +          resource_type: DialogField
    +          ae_namespace: Service/ServiceDialogs
    +          ae_class: DynamicTextAreaBoxes
    +          ae_instance: Disclaimer
    +          ae_message: 
    +          ae_attributes: {}
       - description: 
         display: edit
         label: Configuration

Should the rake tasks match the UI?

**Comment by branic** [comment]
This issue was fixed with PR #20
