### ISSUE TITLE
Test on CloudForms 4

### ISSUE THREAD

**Issue by georgegoh** [rhtconsulting/cfme-rhconsulting-scripts#29]

**Comment by ProxyManagedServices** [comment]
export of policies does not work in CF4

vmdb]# bin/rake rhconsulting:miq_policies:export[/tmp/CFME-build/policies]
/var/www/miq/vmdb/lib/tasks/rhconsulting_reports.rake:19: warning: already initialized constant TagImportExport::UPDATE_FIELDS
/var/www/miq/vmdb/lib/tasks/rhconsulting_policies.rake:19: warning: previous definition of UPDATE_FIELDS was here
/var/www/miq/vmdb/lib/tasks/rhconsulting_tags.rake:19: warning: already initialized constant TagImportExport::UPDATE_FIELDS
/var/www/miq/vmdb/lib/tasks/rhconsulting_reports.rake:19: warning: previous definition of UPDATE_FIELDS was here
rake aborted!
Don't know how to build task 'rhconsulting:miq_policies:export'

**Comment by branic** [comment]
@ProxyManagedServices, I have not been able to reproduce this error. From the messages it looks like there is an issue with the installation of the rake scripts.

Please try to reinstall the latest version of the rake scripts.

**Comment by branic** [comment]
I have tested all of the import/export rake scripts and all are working correctly in CF4.

Test Results:

| Object Type             | Export | Import             |
|-------------------------|--------|--------------------|
| Automation              | Yes    | Yes                |
| Service Dialogs         | Yes    | Yes                |
| Service Catalogs        | Yes    | Yes                |
| Tags                    | Yes    | Yes                |
| Reports                 | Yes    | Yes                |
| Buttons                 | Yes    | Yes (as of PR #42) |
| Roles                   | Yes    | Yes                |
| Policies                | Yes    | Yes                |
| Customization Templates | Yes    | Yes                |
