### ISSUE TITLE
Import example

### ISSUE THREAD

**Issue by branic** [rhtconsulting/cfme-rhconsulting-scripts#32]
The order of the items imported in the example of the readme file will lead to Service Catalog items not being linked to the dialog or automation entry points.

The import of the Service Catalog should be the last import that is performed.

**Comment by jsimonelli** [comment]
fixed in https://github.com/rhtconsulting/cfme-rhconsulting-scripts/commit/62f3e1087d6b0ddd4d43921d393b6346fb0ea7e1
