### ISSUE TITLE
Having problems exporting buttons with cfme 5.5.2.4

### ISSUE THREAD

**Issue by ramrexx** [rhtconsulting/cfme-rhconsulting-scripts#37]
# miqexport buttons /tmp
/var/www/miq/vmdb /var/www/miq/vmdb
[DEPRECATION] `configure` is removed in secure_headers 3.x. Instead use `default`.
rake aborted!
Errno::EISDIR: Is a directory @ rb_sysopen - /tmp
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:29:in `write'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:29:in `export'
/var/www/miq/vmdb/lib/tasks/rhconsulting_buttons.rake:236:in `block (3 levels) in <top (required)>'
Tasks: TOP => rhconsulting:buttons:export
(See full trace by running task with --trace)
/var/www/miq/vmdb

**Comment by jsimonelli** [comment]
@ramrexx which version of cfme was this error from? and what was the full command you ran

**Comment by ramrexx** [comment]
I am using cfme 5.5.2.4. The command i ran was "miqexport buttons /tmp"

**Comment by ramrexx** [comment]
Ok I didn't realize that i needed to specify a filename.  I changed my command to "miqexport buttons /tmp/buttons.yml" and it looks like it worked.
