### ISSUE TITLE
importing of policies not working!

### ISSUE THREAD

**Issue by ramrexx** [rhtconsulting/cfme-rhconsulting-scripts#74]
# miqimport policies policies/

/var/www/miq/vmdb ~
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
/var/www/miq/vmdb/lib/tasks/rhconsulting_policies.rake:18:in `import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_policies.rake:93:in`block (3 levels) in <top (required)>'
Tasks: TOP => rhconsulting:miq_policies:import
(See full trace by running task with --trace)
~
# bin/rake "rhconsulting:miq_policies:import[/root/policies/]" --trace

*\* Invoke rhconsulting:miq_policies:import (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute rhconsulting:miq_policies:import
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
/var/www/miq/vmdb/lib/tasks/rhconsulting_policies.rake:18:in `import'
/var/www/miq/vmdb/lib/tasks/rhconsulting_policies.rake:93:in`block (3 levels) in <top (required)>'
/opt/rh/cfme-gemset/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/opt/rh/cfme-gemset/gems/rake-10.5.0/lib/rake/task.rb:235:in`each'
/opt/rh/cfme-gemset/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/opt/rh/cfme-gemset/gems/rake-10.5.0/lib/rake/task.rb:179:in`block in invoke_with_call_chain'
/opt/rh/rh-ruby23/root/usr/share/ruby/monitor.rb:214:in `mon_synchronize'
/opt/rh/cfme-gemset/gems/rake-10.5.0/lib/rake/task.rb:172:in`invoke_with_call_chain'
/opt/rh/cfme-gemset/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/opt/rh/cfme-gemset/gems/rake-10.5.0/lib/rake/application.rb:150:in`invoke_task'
/opt/rh/cfme-gemset/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/opt/rh/cfme-gemset/gems/rake-10.5.0/lib/rake/application.rb:106:in`each'
/opt/rh/cfme-gemset/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/opt/rh/cfme-gemset/gems/rake-10.5.0/lib/rake/application.rb:115:in`run_with_threads'
/opt/rh/cfme-gemset/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/opt/rh/cfme-gemset/gems/rake-10.5.0/lib/rake/application.rb:78:in`block in run'
/opt/rh/cfme-gemset/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/opt/rh/cfme-gemset/gems/rake-10.5.0/lib/rake/application.rb:75:in`run'
bin/rake:4:in `<main>'
Tasks: TOP => rhconsulting:miq_policies:import
[policies.zip](https://github.com/rhtconsulting/cfme-rhconsulting-scripts/files/555924/policies.zip)

**Comment by branic** [comment]
PR merged that fixes this issue.
