### ISSUE TITLE
/var/www/miq/vmdb/app/models/mixins/supports_feature_mixin.rb:103: warning: key :terminate is duplicated and overwritten on line 111

### ISSUE THREAD

**Issue by itewk** [rhtconsulting/cfme-rhconsulting-scripts#85]
Not sure if this error is caused by these scripts or by something these scripts are depending on but whenever I run them I get this warning printed out for every export command I run.

```
/var/www/miq/vmdb/app/models/mixins/supports_feature_mixin.rb:103: warning: key :terminate is duplicated and overwritten on line 111
```

**Comment by branic** [comment]
@itewk this is a benign warning and will be seen by anything that causes the supports_feature_mixin.rb file to be loaded. The QUERYABLE_FEATURES hash has two keys for :terminate (line 103 and line 111).

In the upstream file this has been fixed. I've opened [BZ1433196](https://bugzilla.redhat.com/show_bug.cgi?id=1433196) for CloudForms 5.7.1
